CREATE TABLE USUARIO(
                        ID NUMBER AUTO_INCREMENT NOT NULL PRIMARY KEY,
                        NOME VARCHAR2(100) NOT NULL,
                        SENHA VARCHAR2(100) NOT NULL,
                        EMAIL VARCHAR2(100) NOT NULL,
                        TELEFONE VARCHAR2(100) NOT NULL);


CREATE TABLE JOGO(
                     ID NUMBER AUTO_INCREMENT NOT NULL PRIMARY KEY,
                     NOME VARCHAR2(100) NOT NULL,
                     CATEGORIA NUMBER NOT NULL,
                     FAIXA_ETARIA VARCHAR2(100) NOT NULL,
                     PLATAFORMA NUMBER NOT NULL,
                     PRECO NUMBER NOT NULL);


CREATE TABLE CATEGORIA(
                          ID NUMBER AUTO_INCREMENT NOT NULL PRIMARY KEY,
                          NOME VARCHAR2(100) NOT NULL);


CREATE TABLE PLATAFORMA(
                           ID NUMBER AUTO_INCREMENT NOT NULL PRIMARY KEY,
                           NOME VARCHAR2(100) NOT NULL);


CREATE TABLE PEDIDO(
                       ID NUMBER AUTO_INCREMENT NOT NULL PRIMARY KEY,
                       JOGO NUMBER NOT NULL,
                       USUARIO NUMBER NOT NULL);


Chaves Estrangeiras

ALTER TABLE JOGO
    ADD CONSTRAINT JOGO_CATEGORIA_FK FOREIGN KEY (CATEGORIA) REFERENCES CATEGORIA(ID);

ALTER TABLE JOGO
    ADD CONSTRAINT JOGO_PLATAFORMA_FK FOREIGN KEY (PLATAFORMA) REFERENCES PLATAFORMA(ID);

ALTER TABLE PEDIDO
    ADD CONSTRAINT PEDIDO_JOGO_FK FOREIGN KEY (JOGO) REFERENCES JOGO(ID);

ALTER TABLE PEDIDO
    ADD CONSTRAINT PEDIDO_USUARIO_FK FOREIGN KEY (USUARIO) REFERENCES USUARIO(ID);